### PR TITLE
fixes #2

### LINKED ISSUE #2: the toggleAll checkbox is not behaving like it should
If there are no active todos, the checkbox should be unchecked  while on the active filter
If there are no completed todos, the checkbox should be unchecked while on the completed filter

Situation 1:
If there are two or more completed todos and you are in the completed filter, toggling one of the todos will uncheck the toggleAll checkbox. This is incorrect

Situation 2:
When there are no active todos and you are on the active filter, the toggleAll checkbox should be unchecked

### PR DESCRIPTION
**Pull request by IvoVermeer**
Signed-off-by: Ivo Vermeer ivovermeer@gmail.com

### CODE REVIEW

File: js/app.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ var app = {
 		return indexFound;
 	},
 	checkCompleted: function ( ) {
-		var totalTodos = this.todos.length;
+		var totalTodos = this.getFilteredTodos().length;
```
Comment (IvoVermeer) [inline js/app.js:94]: This seems to work perfectly!
